# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/rasmith/Documents/oilsticker_cpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/rasmith/Documents/oilsticker_cpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/rasmith/Documents/oilsticker_cpp/CMakeFiles /Users/rasmith/Documents/oilsticker_cpp//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/rasmith/Documents/oilsticker_cpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named oilstickergui

# Build rule for target.
oilstickergui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 oilstickergui
.PHONY : oilstickergui

# fast build rule for target.
oilstickergui/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oilstickergui.dir/build.make CMakeFiles/oilstickergui.dir/build
.PHONY : oilstickergui/fast

#=============================================================================
# Target rules for targets named oilstickergui_autogen_timestamp_deps

# Build rule for target.
oilstickergui_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 oilstickergui_autogen_timestamp_deps
.PHONY : oilstickergui_autogen_timestamp_deps

# fast build rule for target.
oilstickergui_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oilstickergui_autogen_timestamp_deps.dir/build.make CMakeFiles/oilstickergui_autogen_timestamp_deps.dir/build
.PHONY : oilstickergui_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named oilstickergui_autogen

# Build rule for target.
oilstickergui_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 oilstickergui_autogen
.PHONY : oilstickergui_autogen

# fast build rule for target.
oilstickergui_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oilstickergui_autogen.dir/build.make CMakeFiles/oilstickergui_autogen.dir/build
.PHONY : oilstickergui_autogen/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oilstickergui.dir/build.make CMakeFiles/oilstickergui.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oilstickergui.dir/build.make CMakeFiles/oilstickergui.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oilstickergui.dir/build.make CMakeFiles/oilstickergui.dir/main.cpp.s
.PHONY : main.cpp.s

oilstickergui_autogen/mocs_compilation.o: oilstickergui_autogen/mocs_compilation.cpp.o
.PHONY : oilstickergui_autogen/mocs_compilation.o

# target to build an object file
oilstickergui_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oilstickergui.dir/build.make CMakeFiles/oilstickergui.dir/oilstickergui_autogen/mocs_compilation.cpp.o
.PHONY : oilstickergui_autogen/mocs_compilation.cpp.o

oilstickergui_autogen/mocs_compilation.i: oilstickergui_autogen/mocs_compilation.cpp.i
.PHONY : oilstickergui_autogen/mocs_compilation.i

# target to preprocess a source file
oilstickergui_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oilstickergui.dir/build.make CMakeFiles/oilstickergui.dir/oilstickergui_autogen/mocs_compilation.cpp.i
.PHONY : oilstickergui_autogen/mocs_compilation.cpp.i

oilstickergui_autogen/mocs_compilation.s: oilstickergui_autogen/mocs_compilation.cpp.s
.PHONY : oilstickergui_autogen/mocs_compilation.s

# target to generate assembly for a file
oilstickergui_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oilstickergui.dir/build.make CMakeFiles/oilstickergui.dir/oilstickergui_autogen/mocs_compilation.cpp.s
.PHONY : oilstickergui_autogen/mocs_compilation.cpp.s

src/LabelPreview.o: src/LabelPreview.cpp.o
.PHONY : src/LabelPreview.o

# target to build an object file
src/LabelPreview.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oilstickergui.dir/build.make CMakeFiles/oilstickergui.dir/src/LabelPreview.cpp.o
.PHONY : src/LabelPreview.cpp.o

src/LabelPreview.i: src/LabelPreview.cpp.i
.PHONY : src/LabelPreview.i

# target to preprocess a source file
src/LabelPreview.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oilstickergui.dir/build.make CMakeFiles/oilstickergui.dir/src/LabelPreview.cpp.i
.PHONY : src/LabelPreview.cpp.i

src/LabelPreview.s: src/LabelPreview.cpp.s
.PHONY : src/LabelPreview.s

# target to generate assembly for a file
src/LabelPreview.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oilstickergui.dir/build.make CMakeFiles/oilstickergui.dir/src/LabelPreview.cpp.s
.PHONY : src/LabelPreview.cpp.s

src/OilLabelGUI.o: src/OilLabelGUI.cpp.o
.PHONY : src/OilLabelGUI.o

# target to build an object file
src/OilLabelGUI.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oilstickergui.dir/build.make CMakeFiles/oilstickergui.dir/src/OilLabelGUI.cpp.o
.PHONY : src/OilLabelGUI.cpp.o

src/OilLabelGUI.i: src/OilLabelGUI.cpp.i
.PHONY : src/OilLabelGUI.i

# target to preprocess a source file
src/OilLabelGUI.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oilstickergui.dir/build.make CMakeFiles/oilstickergui.dir/src/OilLabelGUI.cpp.i
.PHONY : src/OilLabelGUI.cpp.i

src/OilLabelGUI.s: src/OilLabelGUI.cpp.s
.PHONY : src/OilLabelGUI.s

# target to generate assembly for a file
src/OilLabelGUI.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oilstickergui.dir/build.make CMakeFiles/oilstickergui.dir/src/OilLabelGUI.cpp.s
.PHONY : src/OilLabelGUI.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... oilstickergui_autogen"
	@echo "... oilstickergui_autogen_timestamp_deps"
	@echo "... oilstickergui"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... oilstickergui_autogen/mocs_compilation.o"
	@echo "... oilstickergui_autogen/mocs_compilation.i"
	@echo "... oilstickergui_autogen/mocs_compilation.s"
	@echo "... src/LabelPreview.o"
	@echo "... src/LabelPreview.i"
	@echo "... src/LabelPreview.s"
	@echo "... src/OilLabelGUI.o"
	@echo "... src/OilLabelGUI.i"
	@echo "... src/OilLabelGUI.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

